### ISSUE TITLE
Release 1.1?

### ISSUE THREAD

**Issue by HerbFargus** [mattrixk/es-toolkit#5]
@mattrixk Well I've compiled everything and I think we are ready for our first binary release. What do you think?

**Comment by mattrixk** [comment]
My lunch time isn't far off and I want to spend it changing the gamelists to use the Logo instead of the Mix image, and then fixing Carbon and BaseVid to reflect that. I also want to set up BaseVid to use the `<feature supported>` element for carousel and video, so that's going to take a little testing. I'll let you kow once that's done.

**Comment by HerbFargus** [comment]
Sounds good to me.

**Comment by mattrixk** [comment]
I got my hands on a Pi for testing and I set up a clean RetroPie install last night. I moved the Toolkit Roms folder over to the Pi (complete with gamelist and media). The gamelist worked fine (it showed all the metadata) but none of the images showed up because the gamelist shows the image path as
`<image>~/.emulationstation/roms/nes/media/Ultimate Air Combat (USA)-screenshot.jpg</image>`.
If we change the image path to
`<image>./media/Ultimate Air Combat (USA)-screenshot.jpg</image>` then the images still work on Windows ES, and should work on the Pi too.

I'll test this on Pi tonight, but I have it working on jdrassa's latest Windows build.

**Comment by HerbFargus** [comment]
Good call. That's what I meant to do but just spaced it ;)

**Comment by mattrixk** [comment]
The only reason that I know "./media" works is that a single entry in the NES gamelist (Batman Return of the Joker) had it, while everything else had the "~/.emulationstation..." path.

I've updated the gamelist files in the Toolkit.

**Comment by HerbFargus** [comment]
Anything else left on the to-do list? I know you had mentioned using logos instead of the mix

**Comment by mattrixk** [comment]
I've already changed the gamelists to point to logos instead of mix images on Video View, and made them look adequate in BaseVid, but I'm not too happy with them. I also haven't fixed up Carbon to display them properly. I'll be doing both of those things today. I'll also go through the READMEs and see if there's anything missing.

I've restructured the Toolkit Videos so the file-tree follows the Toolkit (roms/snes/media/video.mp4) so they can all just be copied over at once.

I need to take a look at the UXS profiles, but I don't think I'll have the chance today. I don't think they're that important to everything else yet though. They work with older versions of UXS, but need more testing with the latest version. I also need to play with the paths they use.

**Comment by HerbFargus** [comment]
Uxs2 seems to be straightforward enough, as it overrides the profiles on extraction if it's in the same folder anyhow. Perhaps it may be better to just provide a quick readme tutorial or something with it idk. I assume people wanting to use uxs probably already know how it works. But I'll leave that up to you, I don't really use it anyways.

**Comment by mattrixk** [comment]
Yeah, the UXS stuff can be pretty much left as is, but it's still something I want to look into more when I get the chance. There are new things that can be added to mix images, including tiles for the various genres and number of players.

![uxs v2](http://img15.hostingpics.net/pics/7159416PakUSAimage.png)

Unfortunately I don't think they can be styled.

**Comment by mattrixk** [comment]
I made a fresh RetroPie install on a RPi and copied over the Toolkit files. The Carbon theme broke ES because it was missing the "art" folder which held the fonts, so I added the "art" folder to the repo, as well as adding a "retropie" folder to both Carbon and BaseVid.

Carbon didn't need any extra code for the videos or logos (the marquees look fine where they are, they just looked weird when they were using the Mix image instead of the Logo), so I haven't changed anything there. 

I'm going to have another look through the READMEs, but other than that I think it's good to go.

**Comment by HerbFargus** [comment]
Guess I missed a few things. Thanks for catching them. Let me know when you're ready and I'll package the final binary

**Comment by mattrixk** [comment]
I just gave the READMEs a look over and made some small changes. I think we're good to go.

**Comment by HerbFargus** [comment]
ok I'll get the binaries uploaded. will post when done.

**Comment by HerbFargus** [comment]
alright @mattrixk They are uploaded feel free to review the draft release and release it when you are ready. Then we can close this ticket and create a new post or update the old one on the forum announcing the updates.

**Comment by mattrixk** [comment]
The "ES_Toolkit_v1.1" folder has both an ".emulationstation" folder and a "emulationstation" folder inside. The "." folder has an older version of BaseVid that's missing the "retropie" folder, and it's also missing the new launch bats. It looks like you went to copy the contents of "emulationstation" into "ES_Toolkit_v1.1" but it copied the whole folder instead.

**Comment by HerbFargus** [comment]
Feel like a newb! Will fix.

**Comment by HerbFargus** [comment]
realised the issue. 7zip was adding it to the archive rather than overwriting it. I need to delete it before I create a new one.

**Comment by HerbFargus** [comment]
@mattrixk ok try the latest one. It should be good...

**Comment by mattrixk** [comment]
That's looking great mate. I'd say it's good to go. I just have a few minutes now, but I won't be back at the computer until later tonight. You are welcome to publish the release and make a/update the post on the forum.

**Comment by HerbFargus** [comment]
Since this is your masterpiece I will leave the release and posts to you :) 

At your leisure

**Comment by mattrixk** [comment]
Okay. I've published the release, but I won't have time to make the post until my lunch break. I'm slammed at work.

**Comment by HerbFargus** [comment]
No worries, whenever you get to it. Thanks! I'll close this issue now.
