### ISSUE TITLE
GameBoy game list is empty

### ISSUE THREAD

**Issue by mmatyas** [mattrixk/es-toolkit#6]
Currently [gb/gamelist.xml](https://github.com/mattrixk/es-toolkit/blob/6162725edc44daaf5d5fcf147d20bd28454d089e/emulationstation/.emulationstation/roms/gb/gamelist.xml) doesn't have any meaningful content, even though there *are* GB roms and media files.

**Comment by robertybob** [comment]
I believe this is because the GB's purpose is to be a basic view, where as the other systems are for detailed and video views.

**Comment by mattrixk** [comment]
You are both correct. The Gameboy gamelist was deliberately left empty so that you have a Basic View visible to work with.

However it has given me something to think about. I might make 3 gamelists for each system: Basic, Detailed and Video. That way a user can choose for themselves exactly which ones they want to use.
